#!/bin/bash

# Configuration
GO_VERSION=1.18.10
STATE_SYNC=false
SNAP_SHOT=true
EXTERNAL_ADDRESS="{server_ip}:26656"
MEMPOOL_SIZE=500
PRUNING="custom"
PRUNING_KEEP_RECENT="100"
PRUNING_KEEP_EVERY="2000"
PRUNING_INTERVAL="10"

CHECK=1